### ISSUE TITLE
An error occurred during training

### ISSUE THREAD

**Issue by YangBo0411** [Chenastron/MTUNet#3]
When I trained, I got the following error, can the author help me see how to solve it?

Traceback (most recent call last):
  File "E:\Github project\MTUNet-master\tools\train.py", line 237, in <module>
    main()
  File "E:\Github project\MTUNet-master\tools\train.py", line 207, in main
    model = build_detector(
  File "E:\software\anaconda\envs\multi-task\lib\site-packages\mmdet\models\builder.py", line 58, in build_detector
    return DETECTORS.build(
  File "E:\software\anaconda\envs\multi-task\lib\site-packages\mmcv\utils\registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "E:\software\anaconda\envs\multi-task\lib\site-packages\mmcv\cnn\builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "E:\software\anaconda\envs\multi-task\lib\site-packages\mmcv\utils\registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "CenterNet: 'MyHead is not in the models registry'"

**Comment by nnnnnnml** [comment]
This article is missing the part about multitasking detection and segmentation，if you have,Can you provide it to me?
